### ISSUE TITLE
Error "name 'infinity' is not defined" when using Range

### ISSUE THREAD

**Issue by ageron** [zefhub/zef#39]
When using the `Range` op, I get an error `name 'infinity' is not defined`. This happens even if I provide both bounds:

```
>>> Range(10)  # error
>>> Range(1, 10)  # error
```

**Comment by zeyadkhaled** [comment]
This has been fixed!

It was an import issue where `infinity` wasn't correctly exported.

That being said, @pengwyn probably we can probably move both  `infinity` and `nil` to a specific file under VT as `graph_events.py` doesn't seem to be the correct place for them.

**Comment by ageron** [comment]
Thanks for fixing this.
